ref: data/reference/Homo_sapiens_assembly38.fasta

known_sites:
  - data/vcf/Homo_sapiens_assembly38.dbsnp138.vcf
  - data/vcf/Homo_sapiens_assembly38.known_indels.vcf.gz

hapmap: data/vcf/hapmap_3.3.hg38.vcf.gz
omni: data/vcf/1000G_omni2.5.hg38.vcf.gz
1000G: data/vcf/1000G_phase1.snps.high_confidence.hg38.vcf.gz
dbsnp: data/vcf/Homo_sapiens_assembly38.dbsnp138.vcf
mills: data/vcf/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
